CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    permission1 BOOLEAN                                 NOT NULL,
    permission2 BOOLEAN                                 NOT NULL,
    permission3 BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    admin            BOOLEAN DEFAULT FALSE                   NOT NULL,
    password_expired BOOLEAN DEFAULT FALSE                   NOT NULL,
    totp_enabled     BOOLEAN DEFAULT FALSE                   NOT NULL,
    totp_secret      VARCHAR(255),
    role_id          BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);