ALTER TABLE server_instances
    ADD COLUMN port INT,
    ADD CONSTRAINT uc_server_instances_port UNIQUE (port);

CREATE TABLE app_config
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data JSONB                                   NOT NULL,
    CONSTRAINT pk_app_config PRIMARY KEY (id)
);

CREATE TABLE allocated_ports
(
    port        INTEGER NOT NULL,
    instance_id BIGINT,
    CONSTRAINT pk_allocated_ports PRIMARY KEY (port)
);

ALTER TABLE allocated_ports
    ADD CONSTRAINT FK_ALLOCATED_PORTS_ON_INSTANCE FOREIGN KEY (instance_id) REFERENCES server_instances (id);